In [ ]:
import nltk
nltk.download('treebank')
nltk.download('brown')
nltk.download('universal_tagset')


[nltk_data] Downloading package treebank to /root/nltk_data...
[nltk_data]   Unzipping corpora/treebank.zip.
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package universal_tagset to /root/nltk_data...
[nltk_data]   Unzipping taggers/universal_tagset.zip.


True

In [ ]:
from nltk.corpus import treebank,brown # treebank,brown  are the corpus inbulit

In [ ]:
data1=treebank.tagged_sents(tagset='universal') # output is list of list [[(word),(pos)]] inner list is document contain 2 tuples -word,part of speech

In [ ]:
len(data1)

3914

In [ ]:
data2=brown.tagged_sents(tagset='universal')
len(data2)

57340

In [ ]:
data=data1+data2

In [ ]:
len(data)

61254

In [ ]:
#separte in xi,yi
data

[[('Pierre', 'NOUN'), ('Vinken', 'NOUN'), (',', '.'), ('61', 'NUM'), ('years', 'NOUN'), ('old', 'ADJ'), (',', '.'), ('will', 'VERB'), ('join', 'VERB'), ('the', 'DET'), ('board', 'NOUN'), ('as', 'ADP'), ('a', 'DET'), ('nonexecutive', 'ADJ'), ('director', 'NOUN'), ('Nov.', 'NOUN'), ('29', 'NUM'), ('.', '.')], [('Mr.', 'NOUN'), ('Vinken', 'NOUN'), ('is', 'VERB'), ('chairman', 'NOUN'), ('of', 'ADP'), ('Elsevier', 'NOUN'), ('N.V.', 'NOUN'), (',', '.'), ('the', 'DET'), ('Dutch', 'NOUN'), ('publishing', 'VERB'), ('group', 'NOUN'), ('.', '.')], ...]

In [ ]:
final_sent=[]
final_tags=[]
for doc in data:
    sent=[]
    tags=[]
    for word,tag in doc:
        sent.append(word)
        tags.append(tag)
    final_sent.append(sent)
    final_tags.append(tags)

In [ ]:
final_sent[0]

['Pierre',
 'Vinken',
 ',',
 '61',
 'years',
 'old',
 ',',
 'will',
 'join',
 'the',
 'board',
 'as',
 'a',
 'nonexecutive',
 'director',
 'Nov.',
 '29',
 '.']

In [ ]:
final_tags[0]

['NOUN',
 'NOUN',
 '.',
 'NUM',
 'NOUN',
 'ADJ',
 '.',
 'VERB',
 'VERB',
 'DET',
 'NOUN',
 'ADP',
 'DET',
 'ADJ',
 'NOUN',
 'NOUN',
 'NUM',
 '.']

In [ ]:
len(final_sent),len(final_tags)

(61254, 61254)

In [ ]:
#vocublay
l1=[]
for doc in final_sent:
    for word in doc:
      if word.lower() not in l1:
        l1.append(word.lower())

In [ ]:
l2=[]
for doc in final_tags:
    for tag in doc:
      if tag.lower() not in l2:
        l2.append(tag.lower())

In [ ]:
len(l1),len(l2)

(53232, 12)

In [ ]:
# 2 vectorizier layer for sent,tags
from keras.models import Sequential
from keras.layers import Dense,Flatten,Embedding,LSTM,GRU,TextVectorization,SimpleRNN,InputLayer

In [ ]:
tvs=TextVectorization(standardize='lower',output_mode="int",vocabulary=l1)

In [ ]:
tvt=TextVectorization(standardize='lower',output_mode="int",vocabulary=l2)

In [ ]:
l3=[]
for y in final_sent:
  l3.append(" ".join(y))

In [ ]:
import pandas as pd
sent_df=pd.DataFrame(l3,columns=["sent"])

In [ ]:
l4=[]
for y in final_tags:
  l4.append(" ".join(y))

In [ ]:
tags_df=pd.DataFrame(l4,columns=["tags"])

In [ ]:
sent_df

sent
0      Pierre Vinken , 61 years old , will join the b...
1      Mr. Vinken is chairman of Elsevier N.V. , the ...
2      Rudolph Agnew , 55 years old and former chairm...
3      A form of asbestos once used * * to make Kent ...
4      The asbestos fiber , crocidolite , is unusuall...
...                                                  ...
61249                                     S. J. Perelman
61250                            revulsion in the desert
61251  the doors of the D train slid shut , and as I ...
61252  She was a living doll and no mistake -- the bl...
61253  From what I was able to gauge in a swift , gre...

[61254 rows x 1 columns]

In [ ]:
tags_df

tags
0      NOUN NOUN . NUM NOUN ADJ . VERB VERB DET NOUN ...
1      NOUN NOUN VERB NOUN ADP NOUN NOUN . DET NOUN V...
2      NOUN NOUN . NUM NOUN ADJ CONJ ADJ NOUN ADP NOU...
3      DET NOUN ADP NOUN ADV VERB X X PRT VERB NOUN N...
4      DET NOUN NOUN . NOUN . VERB ADV ADJ ADP PRON V...
...                                                  ...
61249                                     NOUN NOUN NOUN
61250                                  NOUN ADP DET NOUN
61251  DET NOUN ADP DET NOUN NOUN VERB VERB . CONJ AD...
61252  PRON VERB DET VERB NOUN CONJ DET NOUN . DET AD...
61253  ADP DET PRON VERB ADJ ADP NOUN ADP DET ADJ . A...

[61254 rows x 1 columns]

In [ ]:
sen_vec=tvs(sent_df)

In [ ]:
sen_vec

<tf.Tensor: shape=(61254, 271), dtype=int64, numpy=
array([[   2,    3,    4, ...,    0,    0,    0],
       [  19,    3,   20, ...,    0,    0,    0],
       [  28,   29,    4, ...,    0,    0,    0],
       ...,
       [  10, 6599,   22, ...,    0,    0,    0],
       [1642,   37,   13, ...,    0,    0,    0],
       [ 172, 1001, 1327, ...,    0,    0,    0]])>

In [ ]:
tag_vec=tvt(tags_df)

In [ ]:
tag_vec

<tf.Tensor: shape=(61254, 271), dtype=int64, numpy=
array([[ 2,  2,  3, ...,  0,  0,  0],
       [ 2,  2,  6, ...,  0,  0,  0],
       [ 2,  2,  3, ...,  0,  0,  0],
       ...,
       [ 7,  2,  8, ...,  0,  0,  0],
       [13,  6,  7, ...,  0,  0,  0],
       [ 8,  7, 13, ...,  0,  0,  0]])>

In [ ]:
pip install fasttext

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.4/73.4 kB 1.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
Using cached pybind11-2.13.6-py3-none-any.whl (243 kB)
  Created wheel for fasttext: filename=fasttext-0.9.3-cp311-cp311-linux_x86_64.whl size=4313499 sha256=80dc0ced68346277a7c0316880f9b293fd70bfcd47991278b6e80ae736db4d0e
  Stored in directory: /root/.cache/pip/wheels/65/4f/35/5057db0249224e9ab55a513fa6b79451473ceb7713017823c3
Successfully built fasttext


In [ ]:
import fasttext

In [ ]:
model=fasttext.load_model("/content/drive/MyDrive/cc.en.300.bin")

In [ ]:
import numpy as np
embeding_matrix=np.zeros((53234,300)) # emb weights

In [ ]:
"king" in model.words

True

In [ ]:
"pierre" in model.words

True

In [ ]:
model.get_word_vector("pierre")

array([ 0.01890098, -0.04239992, -0.10450727,  0.02859101, -0.00342906,
       -0.05949913, -0.02152638, -0.1374798 , -0.01604277,  0.05145067,
       -0.15094602,  0.08009011,  0.1507111 , -0.06487819,  0.02237451,
       -0.02504544, -0.0410486 , -0.06116504,  0.04065504,  0.04532566,
        0.0121297 , -0.01716452,  0.02870867, -0.02576677,  0.08470068,
       -0.04700381, -0.04729776,  0.01106616, -0.04166317,  0.16687603,
       -0.0123292 ,  0.06678479,  0.04435175, -0.02319454,  0.00647016,
       -0.01348712,  0.03518197,  0.09164504, -0.01989049,  0.002215  ,
        0.08496165,  0.02729364, -0.01085432, -0.09833492,  0.0159589 ,
        0.04365296, -0.03473665,  0.00233076, -0.07410731,  0.07543866,
        0.08286481, -0.10590459,  0.03889842, -0.07867318,  0.03196147,
        0.03456933,  0.05437898, -0.09418815,  0.12851731,  0.01062155,
        0.01893455,  0.03033027,  0.06191111,  0.06733354, -0.08629797,
       -0.04135576,  0.03251836,  0.07173751, -0.01137428,  0.03

In [ ]:
voc={}
for i,word in enumerate(tvs.get_vocabulary()):
  voc.update({word:i})

In [ ]:
for word,i in voc.items():
  if word in model.words:
    embeding_matrix[i]=model.get_word_vector(word)

In [ ]:
embeding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.01890098, -0.04239992, -0.10450727, ...,  0.08609626,
        -0.07368001, -0.06448415],
       ...,
       [-0.02358743, -0.04903779, -0.01356773, ...,  0.0582323 ,
         0.0314977 ,  0.01633622],
       [-0.02613187, -0.08870206,  0.00938397, ...,  0.11142006,
         0.0135748 , -0.04327246],
       [-0.04762868,  0.0085325 ,  0.03504746, ...,  0.02878315,
        -0.01662832, -0.01744141]])

In [ ]:
from keras.layers import InputLayer,TimeDistributed

In [ ]:
model=Sequential()
model.add(InputLayer(shape=(271,)))
model.add(Embedding(53234,300,weights=[embeding_matrix],trainable=False))
model.add(SimpleRNN(50,return_sequences=True))
model.add(TimeDistributed(Dense(14,activation="softmax")))
# TimeDistributed is used  wrapper to allow or sent output as input to the  another denser layer at every timestamp

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ (None, 271, 300)            │      15,970,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ (None, 271, 50)             │          17,550 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed (TimeDistributed)   │ (None, 271, 14)             │             714 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 15,988,464 (60.99 MB)

 Trainable params: 18,264 (71.34 KB)

 Non-trainable params: 15,970,200 (60.92 MB)

In [ ]:
# =yi--one hot encoding

In [ ]:
tvt.get_vocabulary()

['',
 '[UNK]',
 np.str_('noun'),
 np.str_('.'),
 np.str_('num'),
 np.str_('adj'),
 np.str_('verb'),
 np.str_('det'),
 np.str_('adp'),
 np.str_('conj'),
 np.str_('x'),
 np.str_('adv'),
 np.str_('prt'),
 np.str_('pron')]

In [ ]:
from keras.utils import to_categorical # convert one hot encoding

In [ ]:
to_categorical(sen_vec.numpy()).shape

In [ ]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [ ]:
model.fit(sen_vec.numpy(),to_categorical(tag_vec.numpy()),epochs=2,batch_size=32,validation_split=0.2)

Epoch 1/2
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 608s 396ms/step - accuracy: 0.9771 - loss: 0.0764 - val_accuracy: 0.9881 - val_loss: 0.0393
Epoch 2/2
1532/1532 ━━━━━━━━━━━━━━━━━━━━ 681s 436ms/step - accuracy: 0.9856 - loss: 0.0467 - val_accuracy: 0.9919 - val_loss: 0.0264


In [ ]:
model.save('/content/drive/MyDrive/pos_tag.h5')

In [ ]:
text=["Biryani is very tasty and good"]


In [ ]:
tvs(text)

<tf.Tensor: shape=(1, 6), dtype=int64, numpy=array([[  1,  20, 179, 836,  31, 717]])>

In [ ]:
predicted=model.predict(tvs(text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step


In [ ]:
predicted.shape

(1, 6, 14)

In [ ]:
np.argmax(predicted[0],axis=1)

array([ 2,  6, 11,  5,  9,  5])

In [ ]:
out=[]
for y in np.argmax(predicted[0],axis=1):
  out.append(tvt.get_vocabulary()[y])

print(text," ".join(out))

['Biryani is very tasty and good'] noun verb adv adj conj adj


In [ ]:
import pickle
pickle.dump(tvs,open("/content/drive/MyDrive/tvs.pkl","wb"))
pickle.dump(tvt,open("/content/drive/MyDrive/tvt.pkl","wb"))

